apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webshelf-ingress
  namespace: webshelf
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: webshelf.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webshelf-service
            port:
              number: 80
